<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Evan Wong" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Exploratory Project #2: Modeling</title>
    <meta name="generator" content="Hugo 0.61.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/evanwongresume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Exploratory Project #2: Modeling</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>The dataset,diabetes, was found on kaggle, and show shows a collection of data as part of the Pima Indian Diabetes Database. This is a subgroup of the data that consists of females that are aged 21 and above. The dataset column show the number of pregnancies, insulin levels, glucose levels, blood pressure, skin thickness, BMI, and outcome (diabetes or no diabetes). Before analysis, I predict that increases in each of the categories will have a corresponding increase in risk for developing diabetes, but further analysis will be done in order to validate this claim.</p>
<pre><code>##             Df  Pillai approx F num Df den Df    Pr(&gt;F)    
## pregnancies  2 0.34539   3.2703     12    188 0.0002624 ***
## Residuals   98                                             
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##                      Df Sum Sq Mean Sq F value Pr(&gt;F)  
## diabetes$pregnancies  2   6664    3332   3.027  0.053 .
## Residuals            98 107864    1101                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>##                      Df Sum Sq Mean Sq F value Pr(&gt;F)
## diabetes$pregnancies  2   1277   638.7    1.34  0.266
## Residuals            98  46694   476.5</code></pre>
<pre><code>##                      Df Sum Sq Mean Sq F value Pr(&gt;F)
## diabetes$pregnancies  2    846   423.2   1.603  0.207
## Residuals            98  25871   264.0</code></pre>
<pre><code>##                      Df  Sum Sq Mean Sq F value Pr(&gt;F)
## diabetes$pregnancies  2   22105   11052   0.692  0.503
## Residuals            98 1566255   15982</code></pre>
<pre><code>##                      Df Sum Sq Mean Sq F value Pr(&gt;F)
## diabetes$pregnancies  2    128   63.76   0.688  0.505
## Residuals            98   9082   92.67</code></pre>
<pre><code>##                      Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## diabetes$pregnancies  2   2745    1373   13.87 4.99e-06 ***
## Residuals            98   9703      99                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  diabetes$Age and diabetes$pregnancies 
## 
##     high    low    
## low 3e-06   -      
## med 0.00024 0.15719
## 
## P value adjustment method: none</code></pre>
<pre><code>## [1] 0.005</code></pre>
<pre><code>## [1] 0.4012631</code></pre>
<p>A one-way manova test was conducted to determine the effect of numer of pregnacncy (low,med, and high) on 6 dependent variables (glucose, bp, skin thickness, insulin, BMI, and age). Since the number of obersvations in each group was greater than 25, then we can assume normality of the dependent variables. Additionally we can assume that the sample was random and the observations were independent. It is unlikely that the covaraince assumption can be met because the group “high” for number of pregancies has no upper bound, and therefore encompasses a greater range of number of pregnancies which may lead to a greater variance of the corresponding dependent variables relative to the low and med groups. We can also assume that there are no unusual outliers. Also, it is unlikely that the dependent variables were not correlated since they are all health indicators, and they all typically increase as age increases. The results of the manova indicated that at least one of the mean values of the dependedt variables differes significantly from the number of pregancies (p=0.0002624) even after bonferri adjustment since p remains larger than 0.005.</p>
<p>Post ANOVA tests were performed in order to determine which of these dependent variables were statistically significant with respect to number of pregnancies, and it was found that only the age was statistically significant (p=4.99e-06). Post-hoc test indicate that the age was statistically significant between the low and high group (3e-06) and the med and high group (p=0.00024), but not statistically significant between the low and med groups (p=0.15719).</p>
<p>A total of 10 tests were performed, and the probability of having a type 1 error is 40.13%.</p>
<pre><code>## [1] 12.42398</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<pre><code>## [1] 0</code></pre>
<p>The null hypothesis of this test is that the difference in mean age for patients who are classified as high number of pregancies and patients who are classified as low number of pregnancies is zero. The alternative hypothesis is that the difference in mean age between these 2 groups is not zero. The actual mean difference in the sample was 12.423 years, and after conducting the test, this value was determined to be statistically significant with a p-value of 0. This can be seen in the histogram in which the red line is the value of the test statistic (doesn’t even show up on grpah). Therefore, we can reject the null hypothesis and conclude that the value of difference in mean age between the patients with high number of pregnancies and the low number of pregnancies is not zero.</p>
<pre><code>## 
## Call:
## lm(formula = BMI ~ c_glucose * c_bp * c_insulin, data = diabetes)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -33.000  -4.890  -0.017   5.929  17.569 
## 
## Coefficients:
##                            Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)               3.233e+01  9.682e-01  33.395   &lt;2e-16 ***
## c_glucose                 3.065e-02  2.921e-02   1.049   0.2967    
## c_bp                      1.122e-01  6.084e-02   1.845   0.0682 .  
## c_insulin                 2.113e-02  1.287e-02   1.642   0.1039    
## c_glucose:c_bp           -3.535e-03  1.830e-03  -1.932   0.0564 .  
## c_glucose:c_insulin      -3.329e-04  2.150e-04  -1.548   0.1249    
## c_bp:c_insulin            2.333e-04  8.083e-04   0.289   0.7735    
## c_glucose:c_bp:c_insulin  1.041e-05  1.749e-05   0.595   0.5531    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.459 on 93 degrees of freedom
## Multiple R-squared:  0.2773, Adjusted R-squared:  0.223 
## F-statistic: 5.099 on 7 and 93 DF,  p-value: 6.237e-05</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-1.png" width="672" /><img src="/Project2_files/figure-html/unnamed-chunk-4-2.png" width="672" /><img src="/Project2_files/figure-html/unnamed-chunk-4-3.png" width="672" /><img src="/Project2_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<pre><code>## Loading required package: zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;zoo&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     as.Date, as.Date.numeric</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 3.9455, df = 7, p-value = 0.786</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-5.png" width="672" /></p>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-4-6.png" width="672" /></p>
<pre><code>## 
## t test of coefficients:
## 
##                             Estimate  Std. Error t value Pr(&gt;|t|)    
## (Intercept)               3.2333e+01  1.0475e+00 30.8679   &lt;2e-16 ***
## c_glucose                 3.0652e-02  3.4095e-02  0.8990   0.3710    
## c_bp                      1.1225e-01  9.3233e-02  1.2039   0.2317    
## c_insulin                 2.1135e-02  1.3650e-02  1.5484   0.1249    
## c_glucose:c_bp           -3.5348e-03  2.9978e-03 -1.1791   0.2413    
## c_glucose:c_insulin      -3.3295e-04  2.1864e-04 -1.5228   0.1312    
## c_bp:c_insulin            2.3333e-04  1.1823e-03  0.1974   0.8440    
## c_glucose:c_bp:c_insulin  1.0414e-05  2.4022e-05  0.4335   0.6656    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## Likelihood ratio test
## 
## Model 1: BMI ~ c_glucose + c_bp + c_insulin
## Model 2: BMI ~ c_glucose * c_bp * c_insulin
##   #Df  LogLik Df  Chisq Pr(&gt;Chisq)  
## 1   5 -360.23                       
## 2   9 -354.81  4 10.837    0.02846 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>For every 1 unit increase in glucose level, there is a corresponding 3.065e-02 increase in BMI. For every 1 unit increase in blood pressure level, there is a corresponding 1.122e-01 unit increase in BMI. For every one unit increase in insulin level, there is a corresponding 2.113e-02 increase in BMI.</p>
<p>Since the scatterplot for each variable shows no clear curvy pattern with the BMI variable, the dependent variables can be assumed to have a linear relationship with the BMI. Since the breusch-pagan test resulted in a p-value that is learger than 0.05, heteroskedasticity can be assumed to exist in the data. Since the histogram of the residuals appears to be symmetrical and unimodal, we can assume that the distribution is approximately normal, especially since the number of observations is greater than 25.</p>
<p>After running the regression with the robust standard errors, the dependent variables are still not statistically significant in determing the BMI since none of the p-values are below 0.05.</p>
<p>27.7% of the variation in BMI can be explained by the glucose, blood pressure, and insulin levels, and this value is determined from the summary(fit).</p>
<p>Based on the results of the likelihood ratio test, the interactions between the variables provides a statistically significant improvement in the model when determining the BMI based on the predictor vairbales:glucose,bp, and insulin levels.</p>
<pre><code>##   (Intercept)   glucose        bp   insulin  glucose:bp glucose:insulin
## 1    19.34471 0.1846927 0.2868069 0.2686339 0.002702824     0.001815886
##    bp:insulin glucose:bp:insulin
## 1 0.003790132       2.609459e-05</code></pre>
<p>Compared to both the original standard errors and the robust standard errors, the bootsrapped standard errors are larger for all dependent variables:glucose,blood pressure, and insulin levels. The bootstrapped standard error of the interaction between glucose and blood pressure was greater than the original standard error, but smaller than the robust standard errors. The bootstrapped standard error of the interaction between glucose and insulin was larger than both the original and robust standard erros. The bootstraped standard error of the interaction between bloof pressure and insulin was greater than both the original and robust standard errors. Lastly the bootsrapped standard error of the interaction between glucose, blood pressure, and insulin was larger than both the original and robust standard errors. Since the bootstrapped standard errors are larger compared to the original and the robust standard errors, the p-values were mostly larger as well.</p>
<pre><code>## 
## z test of coefficients:
## 
##               Estimate Std. Error z value  Pr(&gt;|z|)    
## (Intercept) -5.7559841  1.2360724 -4.6567 3.214e-06 ***
## Age          0.0464011  0.0228345  2.0321 0.0421479 *  
## glucose      0.0296765  0.0089107  3.3304 0.0008671 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre><code>## [1] 1.047494</code></pre>
<pre><code>## [1] 1.030121</code></pre>
<pre><code>##      prediction
## truth   0   1 Sum
##   0    55   8  63
##   1    17  21  38
##   Sum  72  29 101</code></pre>
<pre><code>## [1] 0.7524752</code></pre>
<pre><code>## [1] 0.5526316</code></pre>
<pre><code>## [1] 0.8730159</code></pre>
<pre><code>## [1] 0.7241379</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre><code>## # A tibble: 101 x 3
##      prob prediction truth
##     &lt;dbl&gt;      &lt;dbl&gt; &lt;fct&gt;
##  1 0.722           1 1    
##  2 0.142           0 0    
##  3 0.761           1 1    
##  4 0.105           0 0    
##  5 0.460           0 1    
##  6 0.285           0 0    
##  7 0.0967          0 1    
##  8 0.269           0 0    
##  9 0.928           1 1    
## 10 0.613           1 1    
## # ... with 91 more rows</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-6-2.png" width="672" /></p>
<pre><code>##   PANEL group AUC
## 1     1     1  NA
## 2     1     2  NA</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.7519048 0.5533333 0.8785714 0.7266667 0.7984524</code></pre>
<p>Every one unit increase in age multiplies the odds of diabetes by 1.047, and every one unit increase in glucose level multiplies the odds of diabetes by 1.03. The accuracy of the model is 75.2%. The sensitivity of the model is 55.2%. The specificity of the model is 87.3%. The precision of the model is 72.4%.</p>
<p>Since the area under the ROC curve is 0.768, the model is fair at predicting the outcome of diabetes.</p>
<p>After performing the 5 fold cross valdation, the out of sample accuracy, sensitivty, specificity, and recall are 75.2%, 53.4%, 87.7% and 68.4% respectively.</p>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 3.0</code></pre>
<pre><code>## 8 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                         s0
## (Intercept)    -3.29902328
## pregnancieslow  .         
## pregnanciesmed  .         
## glucose         0.01504561
## bp              .         
## insulin         .         
## BMI             0.01317087
## Age             0.01611955</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.7614286 0.6233333 0.8500000 0.7095238 0.8163420</code></pre>
<p>After running the lasso regression, it was determined that only glucose, BMI, and age were important in determing the outcome of diabetes. After rerunning a 5-fold cross validation test with these variables, the accuracy of the model increased to 79.9% compared to the previous 75.2% which was based on a regression with just age and glucose.</p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
